# Generated by Django 6.0.2 on 2026-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='jti',
            field=models.CharField(db_index=True, default='', max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='token_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
