# Generated by Django 6.0.2 on 2026-04-16 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blacklistedtoken_session_id_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='token_family',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
